name: 'Purge cache existing in jsDelivr Network'
author: 'PiQuark6046 and contributors'
description: 'Clone your GitHub repo into jsDelivr Network to enhance transmission speed'

inputs:
  branches:
    description: 'The your branches that you want to purge cache existing in jsDelivr'
    required: false
    default: 'latest'

runs:
  using: 'composite'
  steps:
    - name: Run program
      env:
        GITHUB_TOKEN: ${{ github.token }}
        REPO: ${{ github.repository }}
        CI_WORKSPACE_PATH: ${{ github.workspace }}
        CI_ACTION_PATH: ${{ github.action_path }}
      run: |
        npm run ci -- --gh-token "$GITHUB_TOKEN" --repo "$REPO" --ci-workspace-path "$CI_WORKSPACE_PATH" --ci-action-path "$CI_ACTION_PATH"
      shell: bash
      working-directory: ${{ github.action_path }}